language: ruby
rvm:
  - 2.7.1
before_install:
  - gem install bundle:2.2.30
script:
  - bundle update --bundler
  - bundle exec rake db:migrate
  - bundle exec rspec spec
  - bundle exec cucumber
branches:
  only:
    - master