language: ruby
rvm:
  - 2.7.1
before_install:
  - bundle config set --local deployment 'true'
  - bundle config --local deployment true
  - gem install bundler:2.2.30
script:
  - bundle update --bundler
  - bundle exec rake db:migrate
  - bundle exec rspec spec
  - bundle exec cucumber
branches:
  only:
    - master