language: ruby
rvm:
  - 2.7.1
script:
  - gem install bundler:2.2.30
  - bundle update --bundler
  - bundle exec rake db:migrate
  - bundle exec rspec spec
  - bundle exec cucumber
branches:
  only:
    - master