default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: development

test:
  <<: *default
  database: test

production:
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>
  database: production